export const FARMER_ROUTES = {
  home: '/farmer',
  login: '/farmer/login',
  signup: '/farmer/signup',
  onboarding: '/farmer/onboarding',
  listProduce: '/farmer/list-produce',
  listings: '/farmer/listings',
  listingDetail: (id: string) => `/farmer/listings/${id}` as const,
  listingEdit: (id: string) => `/farmer/listings/${id}/edit` as const,
  listingMatches: (id: string) => `/farmer/listings/${id}/matches` as const,
  offers: '/farmer/offers',
  offerDetail: (id: string) => `/farmer/offers/${id}` as const,
  transactions: '/farmer/transactions',
  transactionDetail: (id: string) => `/farmer/transactions/${id}` as const,
  pickups: '/farmer/pickups',
  transportSuggestions: '/farmer/transport-suggestions',
  advisory: '/farmer/advisory',
  notifications: '/farmer/notifications',
  profile: '/farmer/profile',
  settings: '/farmer/settings',
  help: '/farmer/help',
  more: '/farmer/more',
} as const;

export const BUYER_ROUTES = {
  home: '/buyer',
  login: '/buyer/login',
  signup: '/buyer/signup',
  onboarding: '/buyer/onboarding',
  marketplace: '/buyer/marketplace',
  marketplaceDetail: (id: string) => `/buyer/marketplace/${id}` as const,
  compare: '/buyer/compare',
  recommendations: '/buyer/recommendations',
  recommendationDetail: (id: string) => `/buyer/recommendations/${id}` as const,
  demands: '/buyer/demands',
  demandNew: '/buyer/demands/new',
  demandDetail: (id: string) => `/buyer/demands/${id}` as const,
  demandEdit: (id: string) => `/buyer/demands/${id}/edit` as const,
  offers: '/buyer/offers',
  offerDetail: (id: string) => `/buyer/offers/${id}` as const,
  transactions: '/buyer/transactions',
  transactionDetail: (id: string) => `/buyer/transactions/${id}` as const,
  pickups: '/buyer/pickups',
  insights: '/buyer/insights',
  notifications: '/buyer/notifications',
  profile: '/buyer/profile',
  settings: '/buyer/settings',
} as const;

export const AUTH_ROUTES = {
  signup: '/signup',
} as const;

export const ADMIN_ROUTES = {
  login: '/admin/login',
  home: '/admin',
  farmers: '/admin/farmers',
  farmerDetail: (id: string) => `/admin/farmers/${id}` as const,
  buyers: '/admin/buyers',
  buyerDetail: (id: string) => `/admin/buyers/${id}` as const,
  listings: '/admin/listings',
  listingDetail: (id: string) => `/admin/listings/${id}` as const,
  demands: '/admin/demands',
  matches: '/admin/matches',
  matchDetail: (id: string) => `/admin/matches/${id}` as const,
  offers: '/admin/offers',
  offerDetail: (id: string) => `/admin/offers/${id}` as const,
  transactions: '/admin/transactions',
  transactionDetail: (id: string) => `/admin/transactions/${id}` as const,
  transportSuggestions: '/admin/transport-suggestions',
  analytics: '/admin/analytics',
  regionalActivity: '/admin/regional-activity',
  notifications: '/admin/notifications',
  auditLogs: '/admin/audit-logs',
  settings: '/admin/settings',
} as const;
